### ISSUE TITLE
random-rgba and opacity

### ISSUE THREAD

**Issue by KittyGiraudel** [mknadler/randomize.scss#12]
Any reason not to random opacity if `$opacity` is invalid? Currently set to 1.

**Comment by mknadler** [comment]
For cases like this:

SCSS: `div { background: random-rgba((1,1,1), -.3); }`
=> CSS
`div { background: #061fe3; }`

It's an attempt to have the function break gracefully.

My thinking is: if someone were to be calling this function for multiple elements (in a loop, so that it would be generating different colors for each element), and they were passing an opacity value, they would be expecting all generated colors to have identical opacities to one another; falling back to `$opacity: 1` preserves that aspect of the expected result. By comparison, defaulting to `random()` in the case of, e.g., `$opacity: -3` would result in every generated color having different opacities from one another.

**Comment by KittyGiraudel** [comment]
Makes sense, I suppose.
