### ISSUE TITLE
random-between has no @return

### ISSUE THREAD

**Issue by KittyGiraudel** [mknadler/randomize.scss#4]
In a function, it is usually better to always leave a `@return` statement outside of any conditional statements. Or an `@error`. Anyway, something that prevent the compiler from returning:

> Function random-between finished without @return

**Comment by mknadler** [comment]
I'm thinking that there are two different options for how to structure this function. The first option: absolutely exhaustive checks for errors in how the function is used, so that _any_ possible use case would result in either an `@error` or a `@return`. The second option: try to account for the most common missteps, while, as you suggest, having a default `@return`.

I figure the second option is preferable in terms of both ease of implementation and ease of maintenance, so, yeah, I'll be adding in a default case.

**Comment by mknadler** [comment]
fixed in 2cc3fa3b9d5d1c250ad801394653eee90cfa5a77
